FROM python:3.11

ENV TEMPDIR /tmp/pymuon-suite

# install pymuon-suite
RUN git clone https://github.com/muon-spectroscopy-computational-project/pymuon-suite.git ${TEMPDIR}
RUN pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install -r ${TEMPDIR}/requirements.txt && \
    pip install ${TEMPDIR} && \
    rm -rf ${TEMPDIR}

# create working directory
RUN mkdir /home/pymuon-suite
WORKDIR /home/pymuon-suite

# launch to bash, not Python
ENTRYPOINT ["/bin/bash"]